### ISSUE TITLE
Feature request: ability to compress steam, at different temperatures

### ISSUE THREAD

**Issue by clampi** [LovelySanta/FactorioMods#10]
Hello LovelySanta,

Would like to request ability to compress/decompress steam with recipe restriction/specification of temperature. If possible support vanilla and bobpower specific temperatures.

Reason for request.
Not as much bobs but angelsmods have steam-cracking recipes. When faced with bobmodules speedups, it is very easy to reach fluid flows that surpass pipe ability to transfer fluid. The dedicated steam producers also have limited output, usually 60-90/s, which makes scaling up production for said recipes reach a pipe mess state.

**Comment by LovelySanta** [comment]
https://github.com/LovelySanta/FactorioMod-OtherSmallMods/commit/307a82a24c4adea7b8e8ecf2f859354cfa5b7d27 is the first step in this process, allowing fluids being pressurized, even when they are not barrelable.

Tested this by making sure all bob fluids that are barrelable (but not auto_barreled) are pressurizable:
![image](https://user-images.githubusercontent.com/26593477/83338893-df325c80-a2c8-11ea-9bcf-4040e8d44ee9.png)

**Comment by LovelySanta** [comment]
https://github.com/LovelySanta/FactorioMod-OtherSmallMods/commit/14167749f2039d39cc7ad8c702e3f02d58edd0e3 is the second step in this process, allowing temperatures for pressurizing recipes.

In the example below, 2 temperatures have been defined: 165° and 500°, the temperatures of the base game. So from this, 3 recipes have been defined:
- default (min) temperature (15° in this case, anything <165°)
- 165° (up to <500°)
- \>=500° (till max temperature)

![image](https://user-images.githubusercontent.com/26593477/83341753-88884b00-a2e7-11ea-93d3-c572a8079596.png)

**Comment by LovelySanta** [comment]
https://github.com/LovelySanta/FactorioMod-OtherSmallMods/commit/d46cb86ce9dac337d3baedd3bc008a1144857d35 adds support for bob fluids (165°, 315°, 465°, 615°, 765°). Also includes some QoL changes to the recipes in player crafting menu.

**Comment by LovelySanta** [comment]
Fully implemented in the new release!

**Comment by clampi** [comment]
Thank you.

I kinda assumed this is too much work and the request will be declined, so I went ahead and wrote a mod for myself that implements the feature. Different vision of implementation, same result. Usually, hot-fluid-producers produce fluids at a fixed temperature either by recipe or by boiler entity. So a recipe with non degenerated temperature interval for fluid input might catch fluids it should not catch.

As a contributor to Angel's mods, you might consider supporting compression of "liquid-coolant-used" ;). Because a casting array of 16 ultimate-belt of metal sheet create a lot of hot used coolant.

**Comment by LovelySanta** [comment]
> Usually, hot-fluid-producers produce fluids at a fixed temperature either by recipe or by boiler entity. So a recipe with non degenerated temperature interval for fluid input might catch fluids it should not catch.

I chose to try and catch all fluids (up to 0.1 degree precision) to make sure the compressors don't come to a halt due to temperatures being out of range. Assuming you have the correct temperature and are not mixing them, then you should always have 1 temperature, for example the 165°, and that will pressurize to 165° and depressurize to 165° again without any issues.

> As a contributor to Angel's mods, you might consider supporting compression of "liquid-coolant-used" ;). Because a casting array of 16 ultimate-belt of metal sheet create a lot of hot used coolant.

I am aware, but I have to prepare a hot patch for angels, so I just didn't have time to do so. There are also some other fluids (like the liquid smelting fluids and the hot/cold fluids in the deuterium cycles in petrochem. I just quickly added the different temperatures for steam, as this was the example I already implemented for base game, adding some extra temperatures was just a quick addition :D
