### ISSUE TITLE
Pressurized fluids prototypes have invalid temperature relation.

### ISSUE THREAD

**Issue by clampi** [LovelySanta/FactorioMods#14]
Long explanation:
When the pressurized fluid prototype is generated, the code sets maximum temperature to minimum temperature. But, there are 3 temperatures a fluid might have, 2 mandatory (`default_temperature` and `max_temperature`) and 1 optional (`gas_temperature`). The last temperature is used by Factorio only for some visual feedback, so having `gas_temperature > max_temperature` won't generate an error when loading the prototype.

Now, when playing with Pyanodon mods, I noticed a lot of impossible recipes, as in, the ingredient temperature was above the maximum fluid temperature; the fluid ingredient was always a pressurized fluid. Turns out, Py discriminates fluids based on the fluid temperature to decide how to void said fluid, either as a liquid or as a gas. Different voiding entities, different recipe categories. And uses `gas_temperature` as a decider value.

While as a programmer, I find Py code to be incorrect, because it uses a field which is not guaranteed to exist and has no default value, to generate a recipe based upon, it would also help if pressurized fluids prototype won't have such a temperature degenerated fluid. I understood that the intent was to prevent compression of fluids with non-default temperature, such as steam. But now support was added for such fluids (thanks again). You might consider checking `gas_temperature` field and do the less harsh thing :)

**Comment by clampi** [comment]
Just noticed while diffing the releases, that you commented the code that copies default_temperature->max_temperature. Ignore me.

**Comment by LovelySanta** [comment]
The only reason I did set the max temperature to the default temperature is that I didn't want any temperature changes on it, as that was not needed at all. Now that I do support it, I do need the full range as well.
