### ISSUE TITLE
CompressedFluids and Angels componet mode

### ISSUE THREAD

**Issue by peppermor** [LovelySanta/FactorioMods#15]
Pressurized fluids tech is locked behind production and logistic datacores so you cant research it with Angels component mode. Posting here as I now you are maintaining both projects now.

**Comment by LovelySanta** [comment]
Fixed in https://github.com/LovelySanta/FactorioMod-OtherSmallMods/commit/4abb6a2422947c5c2fb7be8bdb74ed8e7a782f11 for the next release. Thanks for the report.
