### ISSUE TITLE
Temperature After Compressor Reduced

### ISSUE THREAD

**Issue by Bear67** [LovelySanta/FactorioMods#16]
One of my Mods (Mark 4 Boiler) produces Steam at 315 Degrees C. After running the Steam through the Compressor the Steam temperature is lowered to 165 degrees C. My Stream engines are not producing the Max output since the steam is too cold, Since they're looking for 315 Steam. Haven't made it to Nuclear yet, but I'd bet I'd have the same problem there, 500 Degrees C Steam.

**Comment by Bear67** [comment]
Also Posted this on the mod portal.

**Comment by Bear67** [comment]
Pull Request #18 fixes this issue.

**Comment by Bear67** [comment]
And #18

**Comment by Bear67** [comment]
Guess I should leave this open until you check out my Pull request?

**Comment by LovelySanta** [comment]
Merged
