### ISSUE TITLE
Blank Displays, Carried over from Mod Portal Discussion

### ISSUE THREAD

**Issue by dbiser99** [LovelySanta/FactorioMods#19]
Here you go. Both the save file and a screen shot in case it loads normally for you so you know I'm not losing my mind. It was saved in a non-working state and multiple reloads on my end have not resulted in it suddenly working yet. I've definitely walked by and seen the other nixie tubes you can see in the screenshot be blank, but I haven't been able to figure out anything repeatable for that scenario. This sequence when placing new ones seems to be fairly repeatable for me.

(Screenshot 1) Placed (2) 2x Reinforced Nixie Tubes,. Wired to Roboport. Set "monitor" signal to rocket fuel.

(Screenshot 2) Placed 3 regular Nixie Tubes connected to the same signal which you can see work fine

Save file was too big for here so I've gone ahead and included 2 copies...one is the "Screenshot 1" version I started to send. The other is the "Screenshot 2" version I was going to send when I thought to verify the originals were still working ok. Take your pick or use both. They are effectively the same file except for that one difference. Also, they currently have Transport Drones enabled (someone figured out a fix while Klonan works on an official one for 0.18.37.) Running without it shouldn't affect things as the drones are in another part of the map and of course if you stayed at 0.18.36 you shouldn't have a problem.

My next step is going to be to try to get it to work normally. I'll let you know what I did if/when successful.

https://www.dropbox.com/s/3rg8tjgk22dkygg/Freeplay%201B%20with%20Mods%20Nixie%20Issue%20v1.zip?dl=0
https://www.dropbox.com/s/j6hy89010anrtik/Freeplay%201B%20with%20Mods%20Nixie%20Issue%20v2.zip?dl=0

![Nixie Tube Issue Screenshot 2](https://user-images.githubusercontent.com/68525988/88890274-62abf380-d20f-11ea-8e1c-e144275b6b4f.png)
![Nixie Tube Issue Screenshot 1](https://user-images.githubusercontent.com/68525988/88890278-6475b700-d20f-11ea-9ef4-5970b04c5642.png)

**Comment by dbiser99** [comment]
So maybe not that useful after all...I left it here so you had the info and files, but it is in reality working right now...In doing some more testing I realized that I had accidentally NOT programmed rocket fuel into the dual display, but had actually done flamethrower ammo. Still definitely had a problem though as the other displays seen in the "Garage" were the ones that blanked out on me AFTER I had them working correctly.

**Comment by LovelySanta** [comment]
seems like when you placed it, that it did have the correct value in the combinator, and hence it didn't update the graphics, it does seem to work fine...

**Comment by dbiser99** [comment]
Thanks for taking a look. If I run across it again, I'll try to get more detail, but I'm happy writing it off as a glitch right now since it is currently working fine and neither of us can get it to repeat.

**Comment by LovelySanta** [comment]
If you find a way to reproduce it, I can take a look at the code and find where it's bugging out. Feel free to make a new report here or on the portal then.
