### ISSUE TITLE
[Bug][ForceField2] Massive performance hit when changing force field settings

### ISSUE THREAD

**Issue by OvermindDL1** [LovelySanta/FactorioMods#2]
When changing the settings of a force field there is a *massive* performance hit for a few seconds, enough to cause players to start getting the drop indicator.

See image, I placed a single force field emitter, I changed it's range from 3 to 5 (just showing for the test) and the game froze for a couple seconds, then a frame updated (this is when the screenshot was taken), and it froze for a few more seconds, then it ticked a few times then became smooth again.

![image](https://user-images.githubusercontent.com/401605/35190088-c170e788-fe16-11e7-9bc2-ec9745ccecf2.png)

Ignore the picker error, it happens whenever I place a force field and I've already reported it to them:
https://github.com/Nexela/PickerExtended/issues/72

**Comment by OvermindDL1** [comment]
Further testing shows it happens when a field is being 'removed' (like in the above image, the old 'degrading' wall is half vanished, during the entire vanishing process in when it lags like crazy).  Ditto when a field/wall is appearing as well.  Sadly this makes the game unplayable when power issues start happening in and out...  >.>

**Comment by LovelySanta** [comment]
I became aware if this last night, i'm looking into it

**Comment by LovelySanta** [comment]
Do you have this issue in single player too? Or only on multiplayer?

**Comment by LovelySanta** [comment]
Pinpointed the lag to the decay of the old forcefield

**Comment by LovelySanta** [comment]
I've put a fix in the next release, let me know if it reoccur

**Comment by LovelySanta** [comment]
I've tested it on single player and on server, on both the lagg is gone.

**Comment by OvermindDL1** [comment]
Awesome, I'll be testing it soon, real life busy currently.  😅
Thanks much!
