### ISSUE TITLE
Better handling of variable temperature fluids

### ISSUE THREAD

**Issue by Xon** [LovelySanta/FactorioMods#21]
Currently, if a fluid isn't of the exact right temperature, it snaps to the lowest temperature supported instead of the nearest.

This makes barreling steam with multiple temperatures tricky.

**Comment by LovelySanta** [comment]
This is exactly what I do here:
https://github.com/LovelySanta/FactorioMod-OtherSmallMods/blob/4abb6a2422947c5c2fb7be8bdb74ed8e7a782f11/CompressedFluids/prototypes/recipe/compressor-fluid-final-fixes.lua#L150-L243

I figured to do the logic based on temperature behaviour of the base game. This means mainly steam, where higher temperatures would yield more energy. Assume this example: A mod creates steam at 250°. Both the steam engine and steam turbine would accept this fluid. However, the steam engine would produce max energy, similar to steam of temperature 165°. If you would feed it into a steam turbine, it woudn't generate any temperature what so ever as it is lower than the minimum temperature. For this reason it has no influence if I take the lowest possible temperature at all. And this goes well for most mods, with a few exceptions.

If you don't mix fluids, fluids will always have the exact right temperature. You could add intermediate temperatures to solve this problem. However this increases the amount of recipes in the game, which will become problematic if you have many fluids with many different temperatures.

**Comment by Xon** [comment]
I've definitely had the temperature being outputted at something weird when mixing kastorio2/space exploration. I'll see if I can nail it down but once the temps are mixed it is kinda horrible to fix.

**Comment by Xon** [comment]
Any reason to not have temp.max be 1 degree higher than the min? That would handle most cases I've encountered so far.

**Comment by LovelySanta** [comment]
> I've definitely had the temperature being outputted at something weird when mixing kastorio2/space exploration. I'll see if I can nail it down but once the temps are mixed it is kinda horrible to fix.

It should be quite easy to flush the fluid line once with the new fluid system. So that should be do-able...

> Any reason to not have temp.max be 1 degree higher than the min? That would handle most cases I've encountered so far.

Not sure what you mean? I interpret it in 2 cases:
Option 1: have a recipe from fluid_min to temperature T+1 and a second temperature from T to fluid_max
Option 2: have a recipe from fluid_min to fluid_min +1, then from +1 to +2 and keep incrementing till fluid_max

Both options are worse, as in option 1 you'll have unnecessary overlap (they currently overlap perfectly) and option 2 would result in waaay too many fluids, depending on the temperature range and the amount of fluids that are present in a game (for example angels petrochem).
If I still interpreted it wrongly, feel free to correct me, maybe with an example?

**Comment by Xon** [comment]
> It should be quite easy to flush the fluid line once with the new fluid system. So that should be do-able...

I've had multiple nuclear reactors complexes somehow output 500.03/500.01/500.02 temperatures without doing any fluid mixing which is what I find baffle. And somehow this snaps to 165 compressed steam. Despite that 500 is a stock temperature, and at the time the maximum temperature that the mod was instructed to compress.

I was using https://mods.factorio.com/mod/PressurizedFluidsSpaceExplorationBridge to add the extra bits when this happened.

Adding some debugging statements;
```
log('Fluids:'.. serpent.block{compressedFluids.remoteData.fluidTemperatures})
...
log('Temps for '.. fluidName .. ':'.. serpent.block{fluidTemps})
log('Recipes for '.. fluidName .. ':'.. serpent.block{recipeTemps})
```

```
  15.864 Script @__CompressedFluids__/prototypes/recipe/compressor-fluid-final-fixes.lua:58: Fluids:{
  {
    ["se-antimatter-stream"] = {
      10000
    },
    ["se-ion-stream"] = {
      5000
    },
    ["se-particle-stream"] = {
      5000
    },
    ["se-plasma-stream"] = {
      5000
    },
    ["se-proton-stream"] = {
      5000
    },
    ["se-secomppressing-steam"] = {
      15
    },
    ["se-space-coolant-cold"] = {
      -100
    },
    ["se-space-coolant-supercooled"] = {
      -273
    },
    ["se-space-coolant-warm"] = {
      -10
    },
    steam = {
      165,
      500
    }
  }
}
  15.864 Script @__CompressedFluids__/prototypes/recipe/compressor-fluid-final-fixes.lua:65: steam, min:15, max:5000
  15.864 Script @__CompressedFluids__/prototypes/recipe/compressor-fluid-final-fixes.lua:83: Temps for steam:{
  {
    15,
    165,
    500,
    5000
  }
}
  15.864 Script @__CompressedFluids__/prototypes/recipe/compressor-fluid-final-fixes.lua:161: Recipes for steam:{
  {
    {
      max = 164.99000000000001
    },
    {
      max = 499.99000000000001,
      min = 165
    },
    {
      min = 500
    }
  }
}
```

:edit: Never mind; I spotted that Krastorio2 is pushing 415 temperatures which explains the snapping to 165, so I've updated my PR.

**Comment by Xon** [comment]
OK, after some debugging, Space Exploration hits the steam prototype with a max temperature of 5000 and then copies it for a bunch of fluids.

The issue is CompressedFluids is skipping creating a compression/decompression recipe for the max temperature

**Comment by Xon** [comment]
OK, after some debugging, Space Exploration hits the steam prototype with a max temperature of 5000 and then copies it for a bunch of fluids. CompressedFluids is also (sanely) ignoring force temperatures above the maximum.

And Krastorio2 was messing with me as the heat-exchanger outsputs 415 temperatures which explains the snapping to 165, so I've updated my PR.

A possible issue is CompressedFluids is skipping creating a compression/decompression recipe for the max temperature.

**Comment by Xon** [comment]
Any reason to not crawl `data.raw["boiler"][XXX].target_temperature` to discover boilers which output fluids with a temperature?

:edit: Yuck, need to discover what fluids the boiler accepts. ugh.

**Comment by LovelySanta** [comment]
> A possible issue is CompressedFluids is skipping creating a compression/decompression recipe for the max temperature.

It shouldn't skip it... This should set a max temperature for each fluid, except the last one, the last one will go up till the max temperature. This way the recipe will do for example "steam input >= 500° -> pressurized steam of 500°".
https://github.com/LovelySanta/FactorioMod-OtherSmallMods/blob/6026d52be6f51361fffa655fd0ae311f949d60db/CompressedFluids/prototypes/recipe/compressor-fluid-final-fixes.lua#L152-L157

For debugging purposes, you could comment out this next line, such that all the recipes will be visible in the player crafting menu, that way you can easily see all the recipes ingame.
https://github.com/LovelySanta/FactorioMod-OtherSmallMods/blob/6026d52be6f51361fffa655fd0ae311f949d60db/CompressedFluids/prototypes/recipe/compressor-fluid-final-fixes.lua#L164

> Any reason to not crawl `data.raw["boiler"][XXX].target_temperature` to discover boilers which output fluids with a temperature?

That looks like a nice idea... you can find the fluid it's outputting on the fluid port.... However there are many other modded entities that are not boilers (but just regular assemblers/furnaces) which output fluids at different temperatures... I would have to find all of them, and even then, I wouldn't catch any use case, as other mods could still change it afterwards... I rather keep it in this controlled way.

**Comment by Xon** [comment]
> It shouldn't skip it... This should set a max temperature for each fluid, except the last one, the last one will go up till the max temperature. This way the recipe will do for example "steam input >= 500° -> pressurized steam of 500°".

The 5000C temperature definitely wasn't showing up in the `recipeTemps` table when I had SE & K2 enabled and was trying to add it to the list. I'll do a bit more testing however

**Comment by LovelySanta** [comment]
The remote interface will always add them to the list, so first check if it is present in that list:
https://github.com/LovelySanta/FactorioMod-OtherSmallMods/blob/6026d52be6f51361fffa655fd0ae311f949d60db/CompressedFluids/modding-interface.lua#L15-L35

The next step before creating the recipes, it will create an ordered list of all temperatures, including the default (min) temperature and the maximum (max) temperature. You should check if the temperature is present in that list.
https://github.com/LovelySanta/FactorioMod-OtherSmallMods/blob/6026d52be6f51361fffa655fd0ae311f949d60db/CompressedFluids/prototypes/recipe/compressor-fluid-final-fixes.lua#L67-L80

I think I found an edge case, where if 5000°C is the max temperature, it will not have a recipe for that max temperature. Can you double check that this maybe could be the case? If this is the case I might have to do some tweaking...

**Comment by LovelySanta** [comment]
as your picture shows in #20, can you check the max temperature of that fluid?

**Comment by Xon** [comment]
From the previous logs;
> steam, min:15, max:5000

It is 5000C, which appears to cause the recipe loop to skip it.

**Comment by LovelySanta** [comment]
Ok, can you quicky upload an empty save with the mods so I can sync up to it for a test? I'll add some test code to #20 to test if my solution I have in mind would work...

**Comment by Xon** [comment]
One empty save with for the mods
[empty_save.zip](https://github.com/LovelySanta/FactorioMod-OtherSmallMods/files/5012085/empty_save.zip)

**Comment by LovelySanta** [comment]
As mentioned in https://github.com/LovelySanta/FactorioMod-OtherSmallMods/pull/20#issuecomment-667671994, In https://github.com/LovelySanta/FactorioMod-OtherSmallMods/pull/20/commits/62e9541b4f412c4b188b70cdbe2bce41656e0a27 I've implemented a fix for this particular issue. Can you check if you have any other unwanted behaviour? I think nothing turns up, the PR is ready to be merged (and a release to be made?)

**Comment by Xon** [comment]
Haven't seen any, if you can do a release I'll throw it up onto the multiplayer server I'm running for some more indepth testing

**Comment by LovelySanta** [comment]
It's released.
