### ISSUE TITLE
[ForceFields2] Error

### ISSUE THREAD

**Issue by maijz128** [LovelySanta/FactorioMods#3]
Sometimes errors occur.
![qq 20180412195319](https://user-images.githubusercontent.com/6248618/38677464-eda5548c-3e90-11e8-9152-1d6b9aee34ca.png)
![qq 20180412203241](https://user-images.githubusercontent.com/6248618/38677472-f30aa882-3e90-11e8-993a-b24320ede04c.png)

**Comment by LovelySanta** [comment]
Thanks for the report. I'll look into this.
You got any save file (and mod list) where i can test this to make sure its not happening again?

Greetings,
lovely_santa

**Comment by LovelySanta** [comment]
I've put up a fix for this, I hope it won't hapen again
