### ISSUE TITLE
[feature request] Have compressor/decompressor entities as assembly machine instead of furnace

### ISSUE THREAD

**Issue by clampi** [LovelySanta/FactorioMods#6]
Hello LS,

While designing a Rocket Fuel factory with complex recipes (Angel&Bob), due to the hurdle of high volume of fluid, I chose to use your mod instead of barreling, just to see how it goes.

In the process, I noticed that once I place the compressor/de-compressor entities, I loose the visual feedback of which liquid is expected to be in what pipe. Given that the factory uses > 10 different fluid, that was a problem, trying to design the connections between modules and not mixing fluids. Trying to have the cake and eat it too, come up with a possible solution.

It would be nice if we had an option to have compressor & de-compressor entities be assembly machine instead of furnaces, to make use of the new fluid mixing logic in Factorio 0.17. The visual feedback of what fluid is expected to be in the pipe makes design of complex chemical factories much simpler. Bonus is that it also prevents one to make the wrong connections if a connection would result in different fluid mixing. The downside would be the clutter of the recipes in build menu and the need to manually set-up the recipe.

Would you please consider the above request, if time allows for such an effort?

**Comment by LovelySanta** [comment]
Hi,

My initial reason to **NOT** implement the fluid compressor as an assembling machine is that this requires me to add all the recipes to the player crafting menu, resulting in cluttering up the menu with alot of recipes (equivalent to barreling/unbarreling).

However, with the change of 0.17 mixing feature, i'll add an option (disabled by default) to allow the entity to be swapped to an assembler. That way you can use the fluid mixing feature.

I'll first finish another mod, but it is certainly on my TODO list.

Kind regards,
lovely_santa

**Comment by LovelySanta** [comment]
Implemented in v0.1.11 (https://github.com/LovelySanta/FactorioMod-OtherSmallMods/commit/8793d30612e0b2f1b52cd91e644dcaeb054413b7)
