### ISSUE TITLE
[CompressedFluids] Failed to load

### ISSUE THREAD

**Issue by LovelySanta** [LovelySanta/FactorioMods#8]
![image](https://user-images.githubusercontent.com/26593477/65378801-06f30e80-dcbe-11e9-925e-3fd195f7714b.png)

**Comment by theonlywolfboy** [comment]
[Test.zip](https://github.com/LovelySanta/FactorioMod-OtherSmallMods/files/3699282/Test.zip)
Hi, I'm the one who posted on the mods page, so here is the new save file you asked for.
